# Generated by Django 3.0.5 on 2020-04-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200418_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remote_url',
            field=models.URLField(unique=True),
        ),
    ]
