name: NodeJs application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: |
          cd frontend
          yarn install
      - name: Run Eslint
        run: |
          cd frontend
          yarn run lint
      - name: Run tests
        run: |
          cd frontend
          yarn run test-nopromot
